config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items
  resources :categories, only: [:index, :show]
  resources :users, only: [:show,:new,:create,:destroy] do
    collection do
      get 'logout'
    end
  end
  
  resources :card, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:pay, :done ] do
    member do
      get  "pay",  to: "purchase#pay"
      post "done", to: "purchase#done"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end


  validates :nickname, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]


  has_many :items
  has_many :orders
  has_many :comments
  has_one :profile
  has_one :address
  has_many :sns_credentials
  has_one :card

  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/ 


  validates :nickname,                             presence: true
  validates :family_name_kana,                     length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX}
  validates :first_name_kana,                      length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX} 
  validates :birth_year, :birth_month, :birth_day, presence: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
  
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create, :destroy, :edit]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end


  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  # POST /resource
  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(set_address)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    sign_in(:user, @user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def address_params
  #   params.require(:address).permit(:post_code, :address)
  # end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

private

def set_address
  params.require(:address).permit(:post_code ,:prefecture_code ,:city ,:house_number, :building_name)
end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user_items = Item.where(user: params[:id])
    @user = User.find(params[:id])
  end

  def logout
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side.html.haml
%ul.myPage__menu__list
  %li.myPage__menu__list--myPage
    = link_to "マイページ", user_path(current_user.id), data: {"turbolinks" => false},class: "menu"
  %li.myPage__menu__list--profile
    = link_to "プロフィール","#", data: {"turbolinks" => false},class: "menu"
  %li.myPage__menu__list--myInfo
    = link_to "本人情報","#", data: {"turbolinks" => false},class: "menu"
  %li.myPage__menu__list--sell
    = link_to "出品する", new_item_path, data: {"turbolinks" => false},class: "menu"
  %li.myPage__menu__list--payInfo
    = link_to "支払い方法","/card", data: {"turbolinks" => false},class: "menu"
  %li.myPage__menu__list--signOut
    = link_to "ログアウト", logout_users_path, data: {"turbolinks" => false}, class: "menu"

app/views/users/logout.html.haml
.default-container
  .i-container.clearfix
    .side_bar
      = render "users/side"

    .i-single-middle
      .i-single-middle__inner
        .i-single-middle__content
          = link_to "ログアウト", destroy_user_session_path, method: :delete, data: {"turbolinks" => false}, class: "menu"

app/views/users/show.html.haml
= render 'layouts/nav'
.myPage
  .myPage__wrapper
    - if current_user.id == @user.id
      .sideMenu
        = render 'users/side'
    .myMain
      .myMain__contents
        .myMain__contents__head
          .myMain__contents__head__view
            = image_tag 'material/icon/member_photo_noimage_thumb.png', alt: 'image', height: '60px', width: '60px', class: 'photo'
          .myMain__contents__head__name
            %p
              = @user.nickname
      .mySell
        %p.title 出品した商品
        .pickup_inside_show
          .pickup_lists_show
            -# ここから繰り返し
            - @user_items.each do |item|
              = render partial: "items/item", locals: { item: item }

      .myBuy
        .myBuy__head
          %p 購入した商品
        .trade
          .trading
            %p 取引中
          .pastTrade
            %p 過去の取引
        .trade__box
          %ul.trade__box__items
            %li
              %div.trade__box__items--img
              %div.trade__box__items__info
                .trade__box__items__info--itemName aaaaa
                .trade__box__items__info--itemPrice aaaaa
            %li
              %div.trade__box__items--img
              %div.trade__box__items__info
                .trade__box__items__info--itemName aaaaa
                .trade__box__items__info--itemPrice aaaaa
            %li
              %div.trade__box__items--img
              %div.trade__box__items__info
                .trade__box__items__info--itemName aaaaa
                .trade__box__items__info--itemPrice aaaaa

= render 'layouts/banner'
= render 'layouts/footer'
= render 'layouts/sale-btn'