config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items
  resources :categories, only: [:index, :show]
  resources :users, only: [:show,:new,:create,:destroy] do
    collection do
      get 'logout'
    end
  end
  
  resources :card, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:pay, :done ] do
    member do
      get  "pay",  to: "purchase#pay"
      post "done", to: "purchase#done"
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :category
  belongs_to :brand,   optional: true
  has_many :images,    dependent: :destroy
  has_many :orders
  has_many :comments

  validates :name,            presence: true
  validates :name,            length: { maximum: 40 }
  validates :introduction,    presence: true
  validates :introduction,    length: { maximum: 1000 }
  validates :category_id,     presence: true
  validates :condition,       presence: true
  validates :postage_payer,   presence: true
  validates :prefecture_code, presence: true
  validates :preparation_day, presence: true
  validates :price,           numericality: { only_integer: true, greater_than: 300, less_than_or_equal_to: 9999999 }
  validates :trading,         presence: true
  validates :user_id,         presence: true
  
  scope :name_like, ->(keyword) { where('name LIKE(?)', "%#{keyword}%" )}
  scope :category_like, ->(keyword) { where('category_id LIKE(?)', "%#{keyword}%" )}


end

app/controllers/items/searches_controller.rb
class Items::SearchesController < ApplicationController

  def index
    if params[:keyword].nil?
      @category_items = Item.category_like(params[:format]).order("created_at DESC")
    else
      @items = Item.name_like(params[:keyword]).order("created_at DESC")
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]
  before_action :set_category, only: [:new, :create ,:edit ,:update]
  before_action :set_brand, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :not_owner_move_to_index, only: :edit

  def index
    @newitems = Item.order("created_at DESC").limit(10)
  end

  def new
    @item = Item.new
    @item.images.build
  end

  def create
    @item = Item.new(item_params)
    imgs_params = params[:images][:image]
    respond_to do |format|
      if @item.valid? && (imgs_params.length >= 1) && (imgs_params.length <= 10)
        @item.save
        imgs_params.each do |image|
          @item.images.create(image: image, item_id: @item.id)
        end
        format.html{render action: 'create'}
      else
        @item.images.build
        format.html{render action: 'new'}
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      # 編集した商品情報の更新
      @item.update(item_params)
      
      # 画像を追加した場合の処理
      if params[:images].nil?
      else
        imgs_params = params[:images][:image]
        if (imgs_params.length >= 1) && (imgs_params.length <= 10)
          imgs_params.each do |image|
            Image.create(image: image, item_id: @item.id)
          end
        end
      end
      
      #DBの画像が0になる場合は処理をしないようにする
      db_image = Image.where(item_id: @item.id)
      destroy_images_box = []
      @item.images.each do |destroy_check_image|
        if params[:item][:imag_destroy][:"#{destroy_check_image.id}"] == "1"
          destroy_images_box << destroy_check_image
        end
      end
      
      # データベースのimage数と削除image数を比較
      if db_image.length > destroy_images_box.length
        # 既存の画像を削除した場合の処理
        destroy_images_box.each do |destroy_image|
          destroimage = Image.find_by(id: destroy_image.id)
          destroimage.destroy
        end
      else
        # image数が0になる場合の処理
        format.html{redirect_to edit_item_path, notice: '画像は1枚以上登録してください！'}
      end
    format.html{redirect_to item_path}
    end
  end

  def destroy
    if @item.destroy
    else
    redirect_to item_path
    end
  end

  private
  
  def set_item
    @item = Item.find(params[:id])
  end
  
  def set_category
    @category = Category.all()
  end

  def set_brand
    @brand = []
    # @brand = Bland.all()
  end

  def item_params
    params.require(:item)
    .permit(
      :name,
      :introduction,
      :category_id,
      :brand_id,
      :condition,
      :postage_payer,
      :prefecture_code,
      :preparation_day,
      :price,
    ).merge(
      trading: "販売中",
      user_id: current_user.id
    )
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def not_owner_move_to_index
    redirect_to action: :index unless current_user.id == @item.user_id
  end

end

app/helpers/items/searches_helper.rb
module Items::SearchesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.border
-# 商品名
.item-box
  .item-name
    .item-name__top
      .item-name__top__title
        商品名
      .certainly
        必須
    .item-name__form
      .item-name__form__body
        = f.text_field :name, {class:"item-name__form__body__field", placeholder:"40文字まで", required:"required" } 
  
  -# 商品の説明
  .item-int
    .item-int__top
      .item-int__top__title
        商品の説明
      .certainly
        必須
    .item-int__form
      = f.text_area :introduction, {class: "item-int__form__area", placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",maxlength: '1000', required:"required" }
      -# .item-int__form__count 0/1000
.border
-# 商品の詳細
.item-box
  .item-head 商品の詳細
  -# カテゴリー
  .item-category
    .item-category__top
      .item-category__top__title
        カテゴリー
      .certainly
        必須
    .item-category__form
      .item-category__form__body
        = f.label :category_id, class: "item-category__form__body__label" do
          = f.select :category_id, ["選択してください",["レディース", "1"],["メンズ", "2"],["ベビーキッズ", "3"],["インテリ・住まい・子供", "4"],["本・音楽・ゲーム", "5"],["おもちゃ・ホビーグッズ", "6"],["コスメ・香水・美容", "7"],["家電・スマホ・カメラ", "8"],["スポーツ・レジャー", "9"],["ハンドメイド", "10"],["チケット", "11"],["その他", "12"]],{}, {class: "item-category__form__body__label__select"}
          .item-category__form__body__label__box
            %i.fas.fa-chevron-down.item-category__form__body__label__box__icon

  -# ブランド
  -# .item-brand
  -#   .item-brand__top
  -#     .item-brand__top__title
  -#       ブランド
  -#     .optional
  -#       任意
  -#   .item-brand__form
  -#     .item-brand__form__body
  -#       = f.select :brand_id, options_for_select(@brand.map{|c|[c[:name], c[:id]]}), {include_blank:"例）Dior"}, {class: "item-brand__form__body__select"}
  
  -# 商品の状態
  .item-condition
    .item-condition__top
      .item-condition__top__title
        商品の状態
      .certainly
        必須
    .item-condition__form
      .item-condition__form__body
        = f.label :condition, class: "item-condition__form__body__label" do
          = f.select :condition, ["新品、未使用", "未使用に近い","目立った傷や汚れなし","やや汚れや傷あり","傷や汚れあり","全体的に状態が悪い"],{include_blank:"選択してください"}, {class: "item-condition__form__body__label__select", required:"required" }
          .item-condition__form__body__label__box
            %i.fas.fa-chevron-down.item-condition__form__body__label__box__icon

.border

-# 配送について
.item-box
  .item-head 配送について
  -# 配送料の負担
  .item-post
    .item-post__top
      .item-post__top__title
        配送料の負担
      .certainly
        必須
    .item-post__form
      .item-post__form__body
        = f.label :category, class: "item-post__form__body__label" do
          = f.select :postage_payer, ["送料込み(出品者負担)", "着払い(購入者負担)"], {include_blank:"選択してください"}, {class: "item-post__form__body__label__select", required:"required" }
          .item-post__form__body__label__box
            %i.fas.fa-chevron-down.item-post__form__body__label__box__icon
  
  -# 発送元の地域
  .item-code
    .item-code__top
      .item-code__top__title
        発送元の地域
      .certainly
        必須
    .item-code__form
      .item-code__form__body
        = f.label :prefecture_code, class: "item-code__form__body__label" do
          = f.select :prefecture_code, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"], {include_blank:"選択してください"}, {class:"item-code__form__body__label__select", required:"required" }
          .item-code__form__body__label__box
            %i.fas.fa-chevron-down.item-code__form__body__label__box__icon
  
  -# 発送までの日数
  .item-day
    .item-day__top
      .item-day__top__title
        発送までの日数
      .certainly
        必須
    .item-day__form
      .item-day__form__body
        = f.label :preparation_day, class: "item-day__form__body__label" do
          = f.select :preparation_day, ["1~2日で発送", "2~3日で発送","4~7日で発送"], {include_blank:"選択してください"}, {class: "item-day__form__body__label__select", required:"required" }
          .item-day__form__body__label__box
            %i.fas.fa-chevron-down.item-day__form__body__label__box__icon

.border

-# 価格・出品ボタン
.item-box
  .item-head 価格（¥300〜9,999,999）
  -# 販売価格
  .item-price
    .item-price__text
      .item-price__text__top
        .item-price__text__top__title
          販売価格
        .certainly
          必須
    .item-price__form
      .item-price__form__en ¥
      .item-price__form__body
        = f.label :price, class:"item-price__form__body__lavel" do
          = f.number_field :price, {min: 300, max: 9999999, placeholder:'0', class:"item-price__form__body__lavel__field", required:"required" }
  -# .item-price-error 300以上 9,999,999以下で入力してください
  
  -# 販売手数料
  .item-charge
    .item-charge__text
      .item-charge__text__title
        販売手数料（10%）
    .item-price__charge-calc
      .item-price__charge-calc__data —
  .border
  -# 販売利益
  .item-Sales
    .item-Sales__text
      .item-Sales__text__title
        販売利益
    .item-Sales__charge-calc
      .item-Sales__charge-calc__data —
  
  
  -# 出品ボタン
  .submit-btn
    = f.submit '出品する', class: 'submit-btn__sale'
    = link_to '下書きに保存', "#", data: {"turbolinks" => false}, class: 'submit-btn__draft'
    = link_to 'もどる', "#", data: {"turbolinks" => false}, class: 'submit-btn__return'
  
  -# 注意書き
  .attention
    %p.attention__text
      禁止されている
      = link_to '行為', '#', data: {"turbolinks" => false}, class:'attention__text--color'
      および
      = link_to '出品物', '#', data: {"turbolinks" => false}, class:'attention__text--color'
      を必ずご確認ください。
      = link_to '偽ブランド品', '#', data: {"turbolinks" => false}, class:'attention__text--color'
      や
      = link_to '盗品物', '#', data: {"turbolinks" => false}, class:'attention__text--color'
      などの販売は犯罪であり、法律により処罰される可能性があります。また、出品をもちまして
      = link_to '加盟店規約', '#', data: {"turbolinks" => false}, class:'attention__text--color'
      に同意したことになります。

app/views/items/_item.html.haml
.pickup_list
  %label.pickup_label
    = link_to "/items/#{item.id}", data: {"turbolinks" => false},class:"pickup_link" do
      - if item.trading == "販売中"
        = image_tag item.images.first.image.url ,class:"pickup_imge"
      - else item.trading == "売り切れ"
        .sold_out
          .sold_out__text SOLDOUT
        = image_tag item.images.first.image.url ,class:"pickup_imge_byu"
      .pickup_body
        %p.pickup_body__name #{item.name}
        .pickup_body__data
          %p.pickup_body__data__price #{item.price}
          .pickup_body__data__like-box
            %i.fa.fa-star.pickup_body__data__like-box__icon
            %p.pickup_body__data__like-box__like
              12
        %p.pickup_body__tax (税込)

app/views/items/create.html.haml
.listing-complete
  .l-container.clearfix
    .l-single-middle
      .l-single-middle__top
        %p.the-listing-is-complete 出品が完了しました
      .l-single-middle__inner
        %p.description 出品した商品は「出品した商品」からいつでも見ることができます
        .l-single-middle__inner__content1
          = link_to "続けて出品する", new_item_path, data: {"turbolinks" => false}
        .l-single-middle__inner__content2
          = link_to "出品した商品を見る", item_path(@item.id), data: {"turbolinks" => false}
        .l-single-middle__inner__regist
          = link_to "マイページを見る", user_path(current_user.id), data: {"turbolinks" => false}

app/views/items/destroy.html.haml
= render 'layouts/nav'

.contents_destroy
  .success
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} トップページに戻る

= render 'layouts/banner'
= render 'layouts/footer'

app/views/items/edit.html.haml
.sale

  -# ヘッダー
  .header
    =link_to root_path , data: {"turbolinks" => false},class:"header-link" do
      = image_tag "material/logo/logo.png" ,class:"header-image"
  
  -# メイン
  .main
  
    -# 投稿フォーム
    = form_with(model: @item, local: true, id: "item-dropzone", class: "sell-form dropzone") do |f|
      
      -# 画像投稿機能
      .item-box
        -# 出品画像
        .item-image
          .item-image__top
            .item-image__top__title
              出品画像
            .certainly
              必須
          .item-image__max-upload 最大10枚までアップロードできます
          -# --------------------------------- ここまでnew,edit共通CSS ---------------------------------
          -# 画像投稿フォーム
          .item-image__form
            #preview
              - @item.images.each_with_index do |image, num|
                .item-img
                  .item-img__content
                    = image_tag image.image.url
                  %label
                    .item-img__btn
                      .item-img__btn--delete{id: "delete-num#{num}"} 削除
              #image-container{class: "num-#{@item.images.length}"} 
                %label
                  = f.fields_for :images, @images do |image|
                    .input-area
                      = image.file_field :image, type: 'file', name: "images[image][]", id: "upload-image",style: "display:none"
                      %i.fas.fa-camera
            - @item.images.each_with_index do |image, num|
              = f.check_box :imag_destroy, {name: "item[imag_destroy[#{image.id}]]", class:"delete-num#{num}"}
      = render partial: "form", locals: { f: f }
= render 'layouts/item-footer'

app/views/items/index.html.haml
= render 'layouts/nav'

.main
  .main_top
    .contents
      .contents__subtitle
        人生を変えるフリマアプリ
      .contents__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .contents__btns
        .contents__btns__btn
          = link_to "#", data: {"turbolinks" => false}, class:"contents__btns__btn__app_store" do
            = image_tag "material/btn/app_store.png", class: "contents__btns__btn__app_store--btn"
        .contents__btns__btn
          = link_to "#", data: {"turbolinks" => false}, class:"contents__btns__btn__google_play" do
            = image_tag "material/btn/google_play.png", class: "contents__btns__btn__google_play--btn"


  .inttodactions
    .inttodaction
      %p.subtitle FURIMAが選ばれる3つの理由
      .inttodaction__green_bar
      .inttodaction__lists
        -# ここから繰り返し
        .inttodaction__lists__list
          .inttodaction__lists__list__image
            %span.number 1
            = image_tag "material/pict/pict-reason-01.jpg"
          %a.inttodaction__lists__list__text
            %span 3分
            ですぐに出品
          %p.inttodaction__lists__list__explamation
            スマホで入力するだけで簡単に出品できる！
          -# ここまで繰り返し
        -# ここから繰り返し
        .inttodaction__lists__list
          .inttodaction__lists__list__image
            %span.number 2
            = image_tag "material/pict/pict-reason-02.jpg"
          %p.inttodaction__lists__list__text
            %span シンプル
            で使いやすい
          %p.inttodaction__lists__list__explamation
            めんどくさい入力は必要なく、検索も購入もスムーズ！
          -# ここまで繰り返し
        -# ここから繰り返し
        .inttodaction__lists__list
          .inttodaction__lists__list__image
            %span.number 3
            = image_tag "material/pict/pict-reason-03.jpg"
          %p.inttodaction__lists__list__text
            手数料
            %span 業界最安
          %p.inttodaction__lists__list__explamation
            最大3%でお得に出品&amp;購入！
          -# ここまで繰り返し


  .download
    .download__inside
      %p.download__inside__text-top
        会員数日本一位
      %p.download__inside__text-bottom
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .download__inside__btns
        .download__inside__btns__btn
          = link_to "#", data: {"turbolinks" => false}, class:"download__inside__btns__btn__app_store" do
            = image_tag "material/btn/app_store.png", class: "download__inside__btns__btn__app_store--btn"
        .download__inside__btns__btn
          = link_to "#", data: {"turbolinks" => false}, class:"download__inside__btns__btn__google_play" do
            = image_tag "material/btn/google_play.png", class: "download__inside__btns__btn__google_play--btn" 



  .features
    .feature
      %p.subtitle
        FURIMAの特徴
      .feature__green_bar
      %ul.feature__lists
        -# ここから繰り返し
        %li.feature__lists__list
          .feature__lists__list__imge
            = image_tag "material/icon/icon-01.png"
          %p.feature__lists__list__text 簡単に売り買いできる
          %p.feature__lists__list__explamation
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
          -# ここまで繰り返し
        -# ここから繰り返し
        %li.feature__lists__list
          .feature__lists__list__imge
            = image_tag "material/icon/icon-03.png"
          %p.feature__lists__list__text 売上金は即日振込みに対応
          %p.feature__lists__list__explamation
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
          -# ここまで繰り返し
        -# ここから繰り返し
        %li.feature__lists__list
          .feature__lists__list__imge
            = image_tag "material/icon/icon-04.png"
          %p.feature__lists__list__text 様々な支払いに対応
          %p.feature__lists__list__explamation
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
          -# ここまで繰り返し


  .pickups
    %p.subtitle 新着商品
    .new_items
      = link_to "新規投稿商品一覧", items_searches_path, data: {"turbolinks" => false}, class:"new_items"
    .pickup_inside
      .pickup_lists
        -# ここから繰り返し
        - @newitems.each do |item|
          = render partial: "item", locals: { item: item }
          -# ここまで繰り返し

= render 'layouts/banner'
= render 'layouts/footer'
= render 'layouts/sale-btn'

app/views/items/new.html.haml
.sale

  -# ヘッダー
  .header
    =link_to root_path, data: {"turbolinks" => false},class:"header-link" do
      = image_tag "material/logo/logo.png" ,class:"header-image"
  
  -# メイン
  .main
  
    -# 投稿フォーム
    = form_with(model: @item, local: true, id: "item-dropzone", class: "sell-form dropzone") do |f|
      
      -# 画像投稿機能
      .item-box
        -# 出品画像
        .item-image
          .item-image__top
            .item-image__top__title
              出品画像
            .certainly
              必須
          .item-image__max-upload 最大10枚までアップロードできます
          -# 画像投稿フォーム
          .item-image__form
            #preview
              -# ここから追加画像
              -# .item-img
              -#   .item-img__content
              -#     = image_tag image.image.url
              -#   %label
              -#     .item-img__btn
              -#       .item-img__btn--delete 削除
              -# ここまで追加画像
              .num-0#image-container
                %label
                  = f.fields_for :images do |image|
                    .input-area
                      = image.file_field :image, type: 'file', name: "images[image][]", id: "upload-image", style: "display:none", required:"required" 
                      %i.fas.fa-camera
          -# .error-messages
      = render partial: "form", locals: { f: f }
= render 'layouts/item-footer'

app/views/items/show.html.haml
= render 'layouts/nav'

.wrappera
%nav.breadCrumbs
  .bread
    %ul
      %li
        = link_to 'FURIMA', '/', data: {"turbolinks" => false}
      %li
        = link_to "#{@item.category.name}", '#', data: {"turbolinks" => false}
      %li
        = @item.name

.main
  .main__snow
    .contentLeftqq
    .contentRight
      .topContent
        .itemBox
          %h2.itemBox__name 
            = @item.name
          .itemBox__body
            %ul
              %li.image-main
                -# 商品の販売状態の確認
                - if @item.trading == "売り切れ"
                  .sold_out_box S O L D O U T
                  - @item.images.each_with_index do |image,index|
                    -if index == 0
                      =image_tag image.image.url, class:"item-img-big_sold_out"
                    -else
                  %ul.imaga
                    - @item.images.each_with_index do |image,index|
                      -if index != -1
                        %li.image-small
                          =image_tag image.image.url,class:"item-img-small_sold_out"
                      -else
                - else @item.trading == "販売中"
                  - @item.images.each_with_index do |image,index|
                    -if index == 0
                      =image_tag image.image.url, class:"item-img-big"
                    -else
                  %ul.imaga
                    - @item.images.each_with_index do |image,index|
                      -if index != -1
                        %li.image-small
                          =image_tag image.image.url,class:"item-img-small"
                      -else
          .itemBox__price
            %span ¥  #{@item.price}
            .itemBox__price-detail
              %span  (税込)
              %span  送料込み
          .itemDetail
            =@item.introduction

          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td 
                    = link_to @item.user.nickname, user_path(@item.user.id), data: {"turbolinks" => false}
                %tr
                  %th カテゴリー
                  %td
                    = link_to @item.category.name, items_searches_path(@item.category.id), data: {"turbolinks" => false}
                    -# %br
                    -# = link_to  @item.category.children.pluck(:name)[0], category_path(@item.id), data: {"turbolinks" => false}
                    -# %br
                    -# = link_to @item.category.descendants.pluck(:name)[7], 
                    -# category_path(@item.id)


                    
                -# %tr
                -#   %th ブランド
                -#   %td
                -#     - if @item.brand.nil?
                -#       %p 指定なし
                -#     - else
                -#       = @item.brand.name
                %tr
                  %th 商品のサイズ
                  %td カラムなし
                %tr
                  %th 商品の状態
                  %td 
                    =@item.condition
                %tr
                  %th 配送料の負担
                  %td 送料込み (出品者負担)
                %tr
                  %th 発送料の地域
                  %td
                    = link_to @item.prefecture_code , '#', data: {"turbolinks" => false}
                %tr
                  %th 発送日の目安
                  %td 
                    =@item.preparation_day
          .optionalArea
            %ul
              %li#likebtn.optionalBtn.likeBtn
                = link_to '★お気に入り 0', '#', data: {"turbolinks" => false}
            %ul
              -# 商品の販売状態の確認
              - if @item.trading == "売り切れ"
                .sold_out_box SOLDOUT
              - else @item.trading == "販売中"
                -# 出品者のIDを確認
                - if user_signed_in? && current_user.id != @item.user_id
                  .likebtn.option
                    = link_to '購入に進む', pay_purchase_path(@item.id), data: {"turbolinks" => false}, class: 'buy'
                  .delete_option
                - elsif user_signed_in? && current_user.id == @item.user_id
                  .pickup_body__user
                    = link_to "この商品を削除する", item_path(@item.id), method: :delete, data:{ confirm: '削除しますか？' } , data: {"turbolinks" => false},class: "pickup_body__deletea"
                  .pickup_body__user
                    = link_to "この商品を編集する", edit_item_path(@item.id), data: {"turbolinks" => false} , class: "pickup_body__show"

        .commentBox
          %ul.commentContents
            = form_with url: "#", local: true, method: :get, class: "search-form" do |form|
              .form-box
                = form.text_area :name, class: "hoge"
              %p.noticeMsg 相手のことを考え丁寧なコメントを心がけましょう。<br>不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br
              = form.submit "コメントする" , class: "search-btn"
      %ul.links
        %li.left
          = link_to '前の商品へ', '#', data: {"turbolinks" => false}
        %li.right
          = link_to '後ろの商品へ', '#', data: {"turbolinks" => false}
      .relatedItems
        = link_to "#{@item.category.name} をもっと見る", items_searches_path("#{@item.category.id}"), data: {"turbolinks" => false}

= render 'layouts/banner'
= render 'layouts/footer'
= render 'layouts/sale-btn'