config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items
  resources :categories, only: [:index, :show]
  resources :users, only: [:show,:new,:create,:destroy] do
    collection do
      get 'logout'
    end
  end
  
  resources :card, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:pay, :done ] do
    member do
      get  "pay",  to: "purchase#pay"
      post "done", to: "purchase#done"
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"

  def index
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "index"
  end

  def show
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/add_to.html.haml
.credit-container
  .c-container.clearfix
    .side_bar
      = render "layouts/side"

    .c-single-middle
      .c-single-middle__top
        %p.method-of-patment 支払い方法
      .c-single-middle__inner
        %p.creditlist クレジットカード一覧
        .c-single-middle__inner__content
          = link_to "クレジットカードを追加する", destroy_user_session_path, method: :delete, class: "menu"
        .c-single-middle__inner__regist
          = link_to "支払い方法について ＞", "#", class: "cp-regist-p"
          %i.icon-arrow-right

app/views/card/index.html.haml
.sale

  -# ヘッダー
  .header
    =link_to root_path, data: {"turbolinks" => false},class:"header-link" do
      = image_tag "material/logo/logo.png" ,class:"header-image"

.credit-container
  .c-container.clearfix
    .side_bar
      = render "users/side"

    .c-single-middle
      .c-single-middle__top
        %p.method-of-patment 支払い方法
      .c-single-middle__inner
        %p.creditlist クレジットカード
        .c-single-middle__inner__content
          = link_to "登録済クレジットカードを確認するor登録","/card/new", data: {"turbolinks" => false}, class: "menu"

        .c-single-middle__inner__regist
          = link_to "支払い方法について ＞", "#", data: {"turbolinks" => false}, class: "cp-regist-p"
          %i.icon-arrow-right

= render 'layouts/banner'
= render 'layouts/footer'
= render 'layouts/sale-btn'

app/views/card/new.html.haml
= form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
  .card_info_input
    %label クレジットカード情報入力
    %br
  .card_number
    %label カード番号
  %br
    = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
    %br
  .expiration_date
  %label 有効期限
  %br
  %select#exp_month{name: "exp_month", type: "text"}
    %option{value: ""} --
    %option{value: "1"}01
    %option{value: "2"}02
    %option{value: "3"}03
    %option{value: "4"}04
    %option{value: "5"}05
    %option{value: "6"}06
    %option{value: "7"}07
    %option{value: "8"}08
    %option{value: "9"}09
    %option{value: "10"}10
    %option{value: "11"}11
    %option{value: "12"}12
  %span 月/
  %select#exp_year{name: "exp_year", type: "text"}
    %option{value: ""} --
    %option{value: "2019"}19
    %option{value: "2020"}20
    %option{value: "2021"}21
    %option{value: "2022"}22
    %option{value: "2023"}23
    %option{value: "2024"}24
    %option{value: "2025"}25
    %option{value: "2026"}26
    %option{value: "2027"}27
    %option{value: "2028"}28
    %option{value: "2029"}29
  %span 年
  %br
  .security_code
    %label セキュリティコード
  %br
    = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
  #card_token
    = submit_tag "登録する", id: "token_submit"

app/views/card/show.html.haml
.card_index
  .card_index__form
    .card_index__form--info 登録クレジットカード情報
    %br
    = "**** **** **** " + @default_card_information.last4
    %br
    %label 有効期限
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
    = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      .card_index_form-button
        %button 削除する
        = link_to "マイページに戻る",user_path(current_user.id), data: {"turbolinks" => false},class:"card_index_mypage_button"