config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items
  resources :categories, only: [:index, :show]
  resources :users, only: [:show,:new,:create,:destroy] do
    collection do
      get 'logout'
    end
  end
  
  resources :card, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:pay, :done ] do
    member do
      get  "pay",  to: "purchase#pay"
      post "done", to: "purchase#done"
    end
  end

end

app/views/layouts/_banner.html.haml
.banner
  .banner__inside
    %p.banner__inside__text-top だれでもかんたん、人生を変えるフリマアプリ
    %p.banner__inside__text-bottom 今すぐ無料ダウンロード！
    .banner__inside__btns
      .banner__inside__btns__btn
        = link_to "#", data: {"turbolinks" => false}, class:"banner__inside__btns__btn__app_store" do
          = image_tag "material/btn/app_store.png", class:"banner__inside__btns__btn__app_store--btn"
      .banner__inside__btns__btn
        = link_to "#", data: {"turbolinks" => false}, class:"banner__inside__btns__btn__google_play" do
          = image_tag "material/btn/google_play.png", class:"banner__inside__btns__btn__google_play--btn"

app/views/layouts/_flash.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_footer.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to '会社概要(運営会社)', '#' , data: {"turbolinks" => false},class: "footer-btn"
        %li
          = link_to 'プライバシーポリシー', '#', data: {"turbolinks" => false},class: "footer-btn"
        %li
          = link_to 'FURIMA利用規約', '#', data: {"turbolinks" => false},class: "footer-btn"
        %li
          = link_to 'ポイントに関する特約', '#', data: {"turbolinks" => false},class: "footer-btn"
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to 'カテゴリー一覧', '#', data: {"turbolinks" => false},class: "footer-btn"
        %li
          = link_to 'ブランド一覧', '#', data: {"turbolinks" => false},class: "footer-btn"
    %li.content
      %h2.content__head  ヘルプ&ガイド 
      %ul
        %li
          = link_to 'FURIMAガイド', '#', data: {"turbolinks" => false},class: "footer-btn"
        %li
          = link_to 'FURIMAロゴ利用ガイドライン', '#', data: {"turbolinks" => false},class: "footer-btn"
        %li
          = link_to 'お知らせ', '#', data: {"turbolinks" => false},class: "footer-btn"
  .footer__logo
    = link_to '#', data: {"turbolinks" => false}, class:"logo-btn" do
      = image_tag "material/logo/logo-white.png", class:"logo-img"
  %p 
    %span  &copy; 
    FURIMA

app/views/layouts/_item-footer.html.haml
.footer2
  .footer2-top
    %ul.footer2-lists
      %li.footer2-list
        = link_to '#', data: {"turbolinks" => false} do
          プライバシーポリシー
      %li.footer2-list
        = link_to '#', data: {"turbolinks" => false} do
          FURIMA利用規約
      %li.footer2-list
        = link_to '#', data: {"turbolinks" => false} do
          特定商取引に関する表記
  = link_to "#", data: {"turbolinks" => false}, class:"footer2_logo" do
    = image_tag "material/logo/logo-square.png", class:"footer2_image"
  .copyright &copy; FURIMA, Inc.

app/views/layouts/_nav.html.haml
%header.navHeader
  .navInner
    .mainHeader
      .mainHeaderIcon
        =link_to image_tag("material/logo/logo.png", class: "mainHeaderIconLogo"),root_path, data: {"turbolinks" => false}
      .searchBox
        = form_with url: items_searches_path, local: true, method: :get, class: "search-form"do |form|
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "search-input"
          %label.search-label
            = form.submit "" , class: "search-btn" 
            = image_tag "material/icon/icon-search 1.png", class:"search-icon" 

    .navNavi
      %ul.listsLeft
        %li.search-navs__unit.category

        %li.category
          = link_to "カテゴリー",categories_path, data: {"turbolinks" => false}, class: "nav-category"
          -# %p.parents_list
          -#   - @category_parent.each do |parent|
          -#     = link_to "#{parent.name}", "#", data: {"turbolinks" => false}, class: "parent_category",id: "#{parent.id}"
          -#     .children_list
          -#       - parent.children.each do |child|
          -#         = link_to "#{child.name}", "#", data: {"turbolinks" => false}, class: "child_category",id: "#{child.id}"
          -#         .grand_children_list
          -#           - child.children.each do |grandchild|
          -#             = link_to "#{grandchild.name}", "#", data: {"turbolinks" => false}, class: "grand_child_category",id: "#{grandchild.id}"
        
        %li.brand
          = link_to "ブランド",'#', data: {"turbolinks" => false}, class: "nav-brand"
      - if user_signed_in?
        %ul.listsRight
          %li.login
            = link_to "マイページ",user_path(current_user.id), data: {"turbolinks" => false},class: "nav-btn"
          %li.login
            = link_to "ログアウト", destroy_user_session_path, method: :delete , data: {"turbolinks" => false},class: "nav-btn"
      - else
        %ul.listsRight
          %li.login
            = link_to "ログイン", new_user_session_path, data: {"turbolinks" => false},class: "nav-btn"
          %li.sign_up
            = link_to "新規会員登録", new_user_registration_path, data: {"turbolinks" => false}, class: "nav-btn"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_sale-btn.html.haml
%label.sale-btn
  - if user_signed_in?
    = link_to new_item_path, data: {"turbolinks" => false}, class:"new-sale" do
      .sale-text 出品する
      = image_tag "material/icon/icon_camera.png"
  - else
    = link_to new_user_registration_path, data: {"turbolinks" => false}, class:"new-sale" do
      .sale-text 登録する
      = image_tag "material/icon/icon_camera.png"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FURIMA
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/flash'
    = yield